# Generated by Django 6.1 on 2026-08-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0002_slotmachine_alter_activity_slot_machine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='acceptance',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='rejection',
            field=models.PositiveIntegerField(),
        ),
    ]
